############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

#[[main]]
#name = "Blog"
#url = "/blog"
#weight = 2

[[main]]
name = "Contact"
url = "/contact"
weight = 3

# footer menu
#[[footer]]
#name = "Contact"
#url = "/contact"
#weight = 1
